// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD-pgyWFoV0b8pC7thIuY1vPsy3tok0sg',
    appId: '1:526312248842:web:8e21339443b4643648b1f3',
    messagingSenderId: '526312248842',
    projectId: 'budgetbuddy-a2ed1',
    authDomain: 'budgetbuddy-a2ed1.firebaseapp.com',
    storageBucket: 'budgetbuddy-a2ed1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC09MSxa8jSalCjPfT732NArBWDYMxjBiw',
    appId: '1:526312248842:android:ad773031303ad93c48b1f3',
    messagingSenderId: '526312248842',
    projectId: 'budgetbuddy-a2ed1',
    storageBucket: 'budgetbuddy-a2ed1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD9f9UScbIOLrKeGYKLj0pCSc97WKPx3A',
    appId: '1:526312248842:ios:4bc671e0698e8e0448b1f3',
    messagingSenderId: '526312248842',
    projectId: 'budgetbuddy-a2ed1',
    storageBucket: 'budgetbuddy-a2ed1.appspot.com',
    iosClientId: '526312248842-027mjnr81e7cehk3utemltb2devodpvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD9f9UScbIOLrKeGYKLj0pCSc97WKPx3A',
    appId: '1:526312248842:ios:4bc671e0698e8e0448b1f3',
    messagingSenderId: '526312248842',
    projectId: 'budgetbuddy-a2ed1',
    storageBucket: 'budgetbuddy-a2ed1.appspot.com',
    iosClientId: '526312248842-027mjnr81e7cehk3utemltb2devodpvu.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgetbuddy',
  );
}
